# Generated by Django 5.2.4 on 2025-09-17 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantapp', '0002_category_menu_restaurant_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qauntity', models.CharField(max_length=40)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurantapp.menu', verbose_name='menuid')),
            ],
        ),
    ]
