# Generated by Django 5.2.4 on 2025-09-17 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantapp', '0003_menu_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_no', models.CharField(max_length=20)),
                ('order_status', models.CharField(max_length=30)),
                ('order_date', models.DateField()),
                ('waiterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurantapp.waiter', verbose_name='_waiter_id')),
            ],
        ),
        migrations.CreateModel(
            name='Food_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurantapp.category', verbose_name='categoryid')),
            ],
        ),
        migrations.CreateModel(
            name='Order_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(max_length=30)),
                ('customer_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurantapp.customer_order', verbose_name='customer_order_id')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Restaurantapp.menu', verbose_name='menuid')),
            ],
        ),
    ]
