# Generated by Django 5.2.4 on 2025-10-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantapp', '0004_customer_order_food_item_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='qauntity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='Quantity',
            field=models.IntegerField(),
        ),
    ]
