# Generated by Django 5.2.4 on 2025-11-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurantapp', '0005_alter_menu_price_alter_menu_item_qauntity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='Price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
